In [1]:
import numpy as np

In [2]:
import numpy as np
b = np.array(list(map(int,input().split())))
b1 = np.array(list(map(int,input().split())))
b2 = np.array(list(map(int,input().split())))

In [3]:
print(b1)
print(b2)

[1 2]
[3 4]


In [13]:
b3 = (b1,b2)
b4 = np.transpose(b3)
print(b4)
b5 = np.transpose(b4)
print(b5)
print(b5.flatten())

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
[1 2 3 4]
